# Generated by Django 3.2.10 on 2024-04-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('stipend_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('job_link', models.URLField()),
                ('referred_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('pdf_file', models.BinaryField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('job_ids', models.ManyToManyField(blank=True, to='myapp.Job')),
            ],
        ),
        migrations.CreateModel(
            name='activeJobs',
            fields=[
                ('reports', models.IntegerField(default=0)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
            ],
        ),
    ]
