# Generated by Django 4.2.3 on 2023-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
