# Generated by Django 4.1.10 on 2023-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
