# Generated by Django 3.2.10 on 2023-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('stipend_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_no', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('job_link', models.URLField()),
                ('referred_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='job_ids',
            field=models.ManyToManyField(blank=True, to='myapp.Job'),
        ),
    ]
