# Generated by Django 3.2.10 on 2023-10-14 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20231005_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='application_no',
            new_name='job_type',
        ),
    ]
