# Generated by Django 3.2.10 on 2023-10-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_application_no_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='activeJobs',
            fields=[
                ('reports', models.IntegerField(default=0)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
            ],
        ),
    ]
